# Custo-Benefício de Jogos na Steam: Uma Análise Exploratória do Valor Percebido pelo Jogador.

### OBJETIVO
Analisar os jogos pagos disponíveis na Steam com o propósito de comparar o valor percebido dos títulos em relação ao custo por hora jogada, à avaliação dos usuários e à popularidade estimada, do ponto de vista do jogador interessado em tomar decisões de compra mais informadas, no contexto de uma análise exploratória baseada em dados públicos da plataforma Steam

## 1. Importar libs

In [12]:
%pip install pandas numpy matplotlib

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in .\.venv\Lib\site-packages (2.4.4)
Requirement already satisfied: matplotlib in .\.venv\Lib\site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\.venv\Lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in .\.venv\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\.venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

import warnings
warnings.filterwarnings("ignore")

print("pandas:", pd.__version__)
print("numpy:", np.__version__)
print("matplotlib:", matplotlib.__version__)

pandas: 3.0.2
numpy: 2.4.4
matplotlib: 3.10.8

## 2. Importação do Dataset

O dataset contém informações sobre jogos da plataforma Steam, incluindo variáveis como preço, tempo médio de jogo, avaliações dos usuários e estimativa de popularidade.

O objetivo desta etapa é:
- definir o caminho do arquivo
- carregar os dados em um DataFrame
- visualizar as primeiras linhas para uma inspeção inicial

In [18]:
# Definição do caminho do dataset
CAMINHO_CSV = "steam_games_dataset.csv"

# Carregamento do dataset
df = pd.read_csv(CAMINHO_CSV)

# Exibir as primeiras linhas
df.head()

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,730,Counter-Strike: Global Offensive,Valve,Valve,NaN,7642084,1173003,0,"100,000,000 .. 200,000,000",33852,708,6645,301,0,0,0,1013936
1,1172470,Apex Legends,Respawn,Electronic Arts,NaN,668053,326926,0,"100,000,000 .. 200,000,000",10506,496,935,246,0,0,0,124262
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",NaN,1520457,1037487,0,"100,000,000 .. 200,000,000",23165,717,5622,261,0,0,0,314682
3,1623730,Palworld,Pocketpair,Pocketpair,NaN,358266,22443,0,"50,000,000 .. 100,000,000",3854,835,2213,257,2999,2999,0,18028
4,440,Team Fortress 2,Valve,Valve,NaN,1044264,117208,0,"50,000,000 .. 100,000,000",21244,736,4262,102,0,0,0,43819

## 3. Inspeção Inicial dos Dados

Análise exploratória inicial do dataset com o objetivo de compreender sua estrutura, tipos de dados e possíveis inconsistências.

Serão verificadas:
- dimensões do dataset
- tipos de dados das colunas
- presença de valores ausentes
- visão geral das informações

### 3.1 Dimensão do dataset

In [19]:
print("Dimensão do dataset:", df.shape)

Dimensão do dataset: (10000, 17)

### 3.2 Tipos de dados

In [20]:
df.dtypes

appid                int64
name                   str
developer              str
publisher              str
score_rank         float64
positive             int64
negative             int64
userscore            int64
owners                 str
average_forever      int64
average_2weeks       int64
median_forever       int64
median_2weeks        int64
price                int64
initialprice         int64
discount             int64
ccu                  int64
dtype: object

### 3.3 Informações gerais

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            10000 non-null  int64
 1   name             10000 non-null  str
 2   developer        9967 non-null   str
 3   publisher        9946 non-null   str
 4   score_rank       5 non-null      float64
 5   positive         10000 non-null  int64
 6   negative         10000 non-null  int64
 7   userscore        10000 non-null  int64
 8   owners           10000 non-null  str
 9   average_forever  10000 non-null  int64
 10  average_2weeks   10000 non-null  int64
 11  median_forever   10000 non-null  int64
 12  median_2weeks    10000 non-null  int64
 13  price            10000 non-null  int64
 14  initialprice     10000 non-null  int64
 15  discount         10000 non-null  int64
 16  ccu              10000 non-null  int64
dtypes: float64(1), int64(12), str(4)
memory usage: 1.3 MB

### 3.4 Valores ausentes

In [22]:
df.isnull().sum()

appid                 0
name                  0
developer            33
publisher            54
score_rank         9995
positive              0
negative              0
userscore             0
owners                0
average_forever       0
average_2weeks        0
median_forever        0
median_2weeks         0
price                 0
initialprice          0
discount              0
ccu                   0
dtype: int64

### 3.5 Estatística básica

In [23]:
df.describe()

,appid,score_rank,positive,negative,userscore,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
count,1.000000e+04,5.0,1.000000e+04,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04
mean,9.008700e+05,99.0,1.214202e+04,1.948096e+03,0.036000,1023.689500,112.496300,515.001700,118.949000,1131.326700,1284.141500,8.675800,5.643178e+02
std,7.290494e+05,1.0,9.536926e+04,1.812977e+04,1.671581,4193.287962,638.473189,3508.429257,707.962801,1299.903805,1364.327698,23.476133,1.128781e+04
min,1.000000e+01,98.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
25%,3.365875e+05,98.0,4.310000e+02,1.100000e+02,0.000000,145.000000,0.000000,79.750000,0.000000,99.000000,199.000000,0.000000,0.000000e+00
50%,6.551300e+05,99.0,1.514500e+03,2.950000e+02,0.000000,310.000000,0.000000,210.000000,0.000000,719.000000,999.000000,0.000000,5.000000e+00
75%,1.333238e+06,100.0,4.996750e+03,8.712500e+02,0.000000,817.250000,6.000000,406.000000,6.000000,1799.000000,1999.000000,0.000000,4.500000e+01
max,3.605460e+06,100.0,7.642084e+06,1.173003e+06,95.000000,263340.000000,20080.000000,269193.000000,20080.000000,14999.000000,14999.000000,95.000000,1.013936e+06

### 3.6 Colunas do dataset

In [24]:
df.columns

Index(['appid', 'name', 'developer', 'publisher', 'score_rank', 'positive',
       'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks',
       'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount',
       'ccu'],
      dtype='str')

## 4. Limpeza e Pré-processamento dos Dados

Nesta etapa, os dados são preparados para análise, garantindo consistência e confiabilidade nas métricas calculadas.

As principais ações realizadas são:

- Conversão da variável `owners` de texto para valor numérico
- Ajuste dos valores de preço (centavos → dólares)
- Filtragem de jogos válidos para análise:
  - apenas jogos pagos
  - jogos com tempo de jogo maior que zero
  - jogos com pelo menos uma avaliação

### 4.1 Tratamento da variável `owners`

A variável `owners` é apresentada no dataset como um intervalo de valores, por exemplo:

"100,000 .. 200,000"

Esse formato textual não é adequado para análises quantitativas. Por esse motivo, foi realizada uma transformação para obter um valor numérico representativo.

A estratégia adotada foi calcular o ponto médio do intervalo:

(100000 + 200000) / 2 = 150000

Esse valor passa a representar uma estimativa da quantidade de proprietários do jogo, sendo utilizado como uma proxy de popularidade nas análises subsequentes.

In [25]:
# Função para converter intervalo em ponto médio
def tratar_owners(valor):
    partes = valor.replace(",", "").split("..")
    minimo = float(partes[0].strip())
    maximo = float(partes[1].strip())
    return (minimo + maximo) / 2

# Aplicar no dataframe
df["owners_mid"] = df["owners"].apply(tratar_owners)

# Verificar
df[["owners", "owners_mid"]].head()

                       owners   owners_mid
0  100,000,000 .. 200,000,000  150000000.0
1  100,000,000 .. 200,000,000  150000000.0
2  100,000,000 .. 200,000,000  150000000.0
3   50,000,000 .. 100,000,000   75000000.0
4   50,000,000 .. 100,000,000   75000000.0

### 4.2 Converter preços

In [26]:
df["price_usd"] = df["price"] / 100
df["initialprice_usd"] = df["initialprice"] / 100

df[["price", "price_usd"]].head()

   price  price_usd
0      0       0.00
1      0       0.00
2      0       0.00
3   2999      29.99
4      0       0.00

### 4.3 Filtrar jogos pagos

In [27]:
df_pagos = df[df["price"] > 0].copy()

print("Total original:", len(df))
print("Jogos pagos:", len(df_pagos))

Total original: 10000
Jogos pagos: 7935

### 4.4 Filtrar jogos com tempo válido

In [28]:
df_validos = df_pagos[df_pagos["average_forever"] > 0].copy()

print("Após filtro de tempo:", len(df_validos))

Após filtro de tempo: 7220

### 4.5 Filtrar jogos com avaliação

In [29]:
total_reviews = df_validos["positive"] + df_validos["negative"]

df_validos = df_validos[total_reviews > 0].copy()

print("Após filtro de avaliações:", len(df_validos))

Após filtro de avaliações: 7210

### 4.6 Resultado da limpeza

In [30]:
print("Dataset final:", df_validos.shape)

Dataset final: (7210, 20)

In [31]:
df_validos.head()

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu,owners_mid,price_usd,initialprice_usd
3,1623730,Palworld,Pocketpair,Pocketpair,NaN,358266,22443,0,"50,000,000 .. 100,000,000",3854,835,2213,257,2999,2999,0,18028,75000000.0,29.99,29.99
5,1938090,Call of Duty: Modern Warfare II,"Treyarch, Raven Software, Beenox, High Moon St...",Activision,NaN,419594,294520,0,"50,000,000 .. 100,000,000",5397,639,738,324,3849,6999,45,67419,75000000.0,38.49,69.99
6,1063730,New World: Aeternum,Amazon Games,Amazon Games,NaN,196798,90080,0,"50,000,000 .. 100,000,000",10588,18,3762,18,5999,5999,0,5583,75000000.0,59.99,59.99
7,2358720,Black Myth: Wukong,Game Science,Game Science,NaN,1111720,38378,0,"50,000,000 .. 100,000,000",3268,524,2838,202,5999,5999,0,15004,75000000.0,59.99,59.99
9,550,Left 4 Dead 2,Valve,Valve,NaN,940221,23762,0,"50,000,000 .. 100,000,000",2479,352,543,71,999,999,0,25122,75000000.0,9.99,9.99